.travis.yml
package.json
src/index.test.js
yarn.lock

Based on #1
Only lint&test for now, no release.

add simple .travis with lint and test

---

docs/cases/with_source_code.md
docs/components/Editor.md
package.json
src/components/CollapsibleItem.js
src/components/Editor.js
src/components/UASTViewer.js
src/helpers.js
src/index.js
src/splitProps.js
src/withUASTEditor.js
styles/_editor.scss
styles/_variables.scss
styles/default-theme.scss
yarn.lock

HOC returns only props due need to support different layouts and it's an application responsibility, not a lib.

Add source-code editor and simple integration

---

docs/cases/with_source_code.md
docs/components/Editor.md
package.json
src/components/CollapsibleItem.js
src/components/Editor.js
src/components/UASTViewer.js
src/helpers.js
src/index.js
src/splitProps.js
src/withUASTEditor.js
styles/_editor.scss
styles/_variables.scss
styles/default-theme.scss
yarn.lock

based on #7 
we use this feature to display search results for example.

 support multiple root nodes in UASTViewer

---

docs/cases/with_source_code.md
docs/components/Editor.md
package.json
src/components/CollapsibleItem.js
src/components/Editor.js
src/components/UASTViewer.js
src/helpers.js
src/index.js
src/splitProps.js
src/withUASTEditor.js
styles/_editor.scss
styles/_variables.scss
styles/default-theme.scss
yarn.lock

Based on #7 
If a consumer doesn't provide callback editor will work as read-only one.

Make onChange callback for Editor optional

---

docs/cases/with_source_code.md
docs/components/Editor.md
package.json
src/components/CollapsibleItem.js
src/components/Editor.js
src/components/UASTViewer.js
src/helpers.js
src/index.js
src/splitProps.js
src/withUASTEditor.js
styles/_editor.scss
styles/_variables.scss
styles/default-theme.scss
yarn.lock

Based on #7 
Add expandToNodeId helper and use it in withUASTEditor.
It's current behavior of the dashboard and it makes sense to do by default.

Expand to node

---

README.md

Signed-off-by: Marcelo Novaes <mnovaes@gmail.com>

Clarify meaning of UAST in README.md

---

docs/state.md
docs/state/helpers.md
docs/state/position_index.md
docs/state/transformer.md
src/transformer.js
styleguide.config.js

add documentation for state functions

---

.babelrc
package.json
src/PositionIndex.test.js
src/helpers.test.js
src/index.test.js
yarn.lock

add tests for posIndex and helpers

---

README.md
package.json
yarn.lock

- update readme
- update lock file after merges
- set correct license and homepage in package.json
- add travis rules for deployment

Prepare v0.0.1

---

.travis.yml

add travis rules for deployment

---

src/helpers.js

hotfix makePositionIndexHook, it's broken due to merges.

fix makePositionIndexHook

---

.gitignore
.travis.yml
package.json

Add deployment to github pages

---

README.md

update readme with link to documentation

---

src/components/Editor.js
src/components/UASTViewer.js

Fix: #28
This PR fixes 2 problems the original one from the issue (second commit) and related one of unnecessary update of editor component (first commit).

Fix code selection

---

docs/cases/with_source_code.md
src/components/Editor.js
src/components/Node.js
src/components/UASTViewer.js
src/withUASTEditor.js

Required by https://github.com/bblfsh/dashboard/issues/136

Scroll editor

---

docs/cases/with_source_code.md
docs/example_java_source.js
docs/example_uast.json
styleguide.config.js

Signed-off-by: Maxim Sukharev <maxim@sourced.tech>

update example source code to showcase scrolling

---

package.json
styleguide.config.js
yarn.lock

use scss loader in styleguide

---

src/withUASTEditor.js

That allows to pass any other input instead of JSON we use now.

allow to use custom transformer in withUASTEditor

---

docs/cases/with_source_code.md
styles/_editor.scss

When I click on "show code" everything gets broken:

with source code example: fix layout

---

styles/_variables.scss

New color from https://github.com/bblfsh/dashboard/issues/116

Change default color for hovered node

---

docs/state/uast-v2.md
src/index.js
src/uast-v2/index.js
styleguide.config.js

We decided to return uast from server as a normal tree, not flat one.

change format of uast2

---

src/uast-v2/__snapshots__/index.test.js.snap
src/uast-v2/index.js
src/uast-v2/index.test.js

when the root is array we don't transform it correctly.
needed for https://github.com/bblfsh/web/issues/172

uast2: fix array transformation

---

package.json
src/components/Node.js
yarn.lock

update prettier to 1.15.x

---

docs/cases/controlled.md
docs/cases/uncontrolled.md
docs/components/UASTViewer.md
docs/state/helpers.md
src/components/Node.js
src/components/UASTViewer.js
src/helpers.js
src/withUASTEditor.js

rename uast to flat uast

---

docs/state/helpers.md

add missed documentation for helpers

---

README.md
docs/cases/controlled.md
docs/cases/uncontrolled.md
docs/cases/with_source_code.md
docs/components/FlatUASTViewer.md
docs/components/UASTViewer.md
docs/quick_start.md
src/components/FlatUASTViewer.js
src/components/UASTViewer.js
src/index.js
src/withUASTEditor.js
src/withUASTEditor.test.js
styleguide.config.js

Accept raw json in uast viewer

---

docs/cases/uncontrolled.md
docs/components/FlatUASTViewer.md
docs/components/Node.md
docs/components/UASTViewer.md
src/components/FlatUASTViewer.js
src/components/FlatUASTViewer.test.js
src/components/UASTViewer.js

Fix: #76 
Also updated input in documentation to match default uast2 schema.
Because currently docs are broken: https://uast-viewer.bblf.sh/#/UI%20Components?id=node

Use initial uast prop

---

package.json
yarn.lock

update babel and eslint-plugin-jest

---

src/uast-v2/__snapshots__/index.test.js.snap
src/uast-v2/index.js
src/uast-v2/index.test.js

- added checks for all corner cases
- added unit tests
fix validated using bug reports from https://github.com/bblfsh/web/issues/195 and https://github.com/bblfsh/web/issues/182

fix types resolving in nodeSchema for uast v2
